main:
    path: /
    controller: App\Controller\IndexController::show

login:
    path: /login
    controller: App\Controller\SecurityController::login

login_check:
    path: /login_check
    controller: App\Controller\SecurityController::loginCheckAction

logout:
    path: /logout

registerScreen:
    path: /register
    controller: App\Controller\RegistrationController::register

addEmployeeScreen:
    path: /addEmployee
    controller: App\Controller\EmployeesController::showAddEmployeeForm

mainMenu:
    path: /menu
    controller: App\Controller\IndexController::afterLogin

employeesList:
    path: /employeesList
    controller: App\Controller\EmployeesController::showList

addEmployee:
    path: /addEmployee
    controller: App\Controller\EmployeesController::showAddEmployeeForm

dayReport:
    path: /dayReport
    controller: App\Controller\EmployeesController::showDayReport

hotelsList:
    path: /hotelsList
    controller: App\Controller\HotelsController::showList

addHotel:
    path: /addHotel
    controller: App\Controller\HotelsController::showAddHotelForm

hotelNetworkReport:
    path: /hotelNetworkReport
    controller: App\Controller\HotelsController::showHotelNetworkReport

networkEmployeesList:
    path: /networkEmployeesList
    controller: App\Controller\HotelsController::showNetworkEmployeesList

roomList:
    path: /roomList
    controller: App\Controller\RoomsController::showList

addRoom:
    path: /addRoom
    controller: App\Controller\RoomsController::showAddRoomForm

addReservation:
    path: /addReservation
    controller: App\Controller\ReservationController::showAddReservation

reservationList:
    path: /reservationList
    controller: App\Controller\ReservationController::showList

servicesList:
    path: /servicesList
    controller: App\Controller\ServiceController::showList

addService:
    path: /addService
    controller: App\Controller\ServiceController::showAddService

discountsList:
    path: /servicesList
    controller: App\Controller\ServiceController::showList

warehouse:
    path: /warehouse
    controller: App\Controller\WarehouseController::showWarehouseMenu
itemList:
    path: /warehouseItems
    controller: App\Controller\WarehouseController::showItemsList

addItem:
    path: /addItem
    controller: App\Controller\WarehouseController::showAddItemForm

ordersList:
    path: /orders
    controller: App\Controller\WarehouseController::showOrdersList

fillClientProfileForm:
    path: /clientForm
    controller: App\Controller\ClientsController::fillProfileForm

monthlyReport:
    path: /monthlyReport
    controller: App\Controller\EmployeesController::report

monthlyWarehouseReport:
    path: /monthlyWarehouseReport
    controller: App\Controller\WarehouseController::report

addOrder:
    path: /addOrder
    controller: App\Controller\WarehouseController::showAddOrderForm