main:
    path: /
    controller: App\Controller\IndexController::show

loginScreen:
    path: /login
    controller: App\Controller\LoginController::show

registerScreen:
    path: /register
    controller: App\Controller\RegistrationController::show

mainMenu:
    path: /menu
    controller: App\Controller\IndexController::afterLogin

employeesList:
    path: /employeesList
    controller: App\Controller\EmployeesController::showList

addEmployee:
    path: /addEmployee
    controller: App\Controller\EmployeesController::showAddEmployeeForm

dayReport:
    path: /dayReport
    controller: App\Controller\EmployeesController::showDayReport