main:
    path: /
    controller: App\Controller\IndexController::show

loginScreen:
    path: /login
    controller: App\Controller\LoginController::show

registerScreen:
    path: /register
    controller: App\Controller\RegistrationController::show

mainMenu:
    path: /menu
    controller: App\Controller\IndexController::afterLogin

employeesList:
    path: /employeesList
    controller: App\Controller\EmployeesController::showList

addEmployee:
    path: /addEmployee
    controller: App\Controller\EmployeesController::showAddEmployeeForm

dayReport:
    path: /dayReport
    controller: App\Controller\EmployeesController::showDayReport
    
hotelsList:
    path: /hotelsList
    controller: App\Controller\HotelsController::showList
    
addHotel:
    path: /addHotel
    controller: App\Controller\HotelsController::showAddHotelForm
    
    
hotelNetworkReport:
    path: /hotelNetworkReport
    controller: App\Controller\HotelsController::showHotelNetworkReport
    
networkEmployeesList:
    path: /networkEmployeesList
    controller: App\Controller\HotelsController::showNetworkEmployeesList